title: No Rest in Minecraft
description: No Rest in Minecraft
remote_theme: riggraz/no-style-please

header_pages:
  - about.md

theme_config:
  appearance: auto
  show_description: true

s
minima:
  skin: auto
  social_links:
    - title: GitHub repository
      icon: github
      url: https://github.com/untodesu/nrmc
    - title: The Linux Space Discord
      icon: discord
      url: 
