title: No Rest in Minecraft
author:
  name: NRMC
description: >
  NRMC is a Minecraft Survival Multiplayer (SMP) server
  designed to preserve the "friends-only" feeling of a single
  specific SMP server I was playing from 2018 up until 2022. NRMC
  features almost fully open-source configuration and this has been
  a core feature ever since the server's inception.
remote_theme: jekyll/minima
minima:
  skin: dark
