title: No Rest in Minecraft
description: No Rest in Minecraft
remote_theme: riggraz/no-style-please

header_pages:
  - about.md

theme_config:
  appearance: auto
  back_home_text: home
  date_format: "%Y-%m-%d"
  show_description: true
  lowercase_titles: true
