title: No Rest in Minecraft
description: No Rest in Minecraft
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
header_pages:
  - about.md
minima:
  skin: auto
  social_links:
    - title: GitHub repository
      icon: github
      url: https://github.com/untodesu/nrmc
    - title: The Linux Space Discord
      icon: discord
      url: https://discord.gg/AFe6Acxr78
