#!/bin/sh

instance=${1}
instance_dir="${HOME}/.msmu/${instance}"
instance_config="${instance_dir}/instance.conf"
instance_start_sh="${instance_dir}/start.sh"

shift 1

if screen -list | grep -q ${instance}
then
    >&2 printf "%s: unable to start %s: instance is running\n" ${0} ${instance}
    exit 1
fi

if [ ! -f "${instance_config}" ]
then
    >&2 printf "%s: unable to start %s: instance doesn't exist\n" ${0} ${instance}
    exit 1
fi

# Load variables from config
. $(realpath ${instance_config}) || exit 1

server_cwd=$(realpath ${server_cwd})
server_jar=$(realpath ${server_jar})

if [ -f "${instance_start_sh}" ]
then
    . $(realpath ${instance_start_sh})
fi

cd ${server_cwd}
screen -dm -S ${instance} java -server ${server_jvm_args} -jar ${server_jar} ${server_args} --nogui
exit 0
